server:
  port: 9090

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/springboot-vue?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

#mybatis:
#  mapper-locations: Mapper/UserMapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#    默认情况下，MyBatis会使用数据库表的列名来映射Java对象的属性。如果数据库表的列名采用下划线命名方式（例如，first_name），
#    而对应的Java对象希望使用驼峰命名方式（例如，firstName），
#    那么你可以通过设置 map-underscore-to-camel-case: true 来告诉MyBatis进行这种自动映射
